services:

  mysql:
    image: mysql:8.4
    container_name: library-mysql

    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: library
      MYSQL_PASSWORD: library123
      MYSQL_ROOT_PASSWORD: root123

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "library",
          "-plibrary123"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  library-api:
    image: library-api:1.0.0
    build:
      context: .
      dockerfile: Dockerfile

    container_name: library-api

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:mysql://mysql:3306/library
      DB_USERNAME: library
      DB_PASSWORD: library123

    ports:
      - "8080:8080"

volumes:
  mysql_data: